### ISSUE TITLE
duplicate of onKeyReleased in index.d.ts 

### ISSUE THREAD

**Issue by thomas3577** [hodgef/simple-keyboard#202]
**Simple-keyboard version**
V 2.26.1

**Describe the bug**
When building the Angular App I get the following error message:

`ERROR in ../node_modules/simple-keyboard/build/index.d.ts:150:5 - error TS2300: Duplicate identifier 'onKeyReleased'.

150     onKeyReleased?: (button: string) => any;
        ~~~~~~~~~~~~~
../node_modules/simple-keyboard/build/index.d.ts:185:5 - error TS2300: Duplicate identifier 'onKeyReleased'.

185     onKeyReleased?: () => void;
        ~~~~~~~~~~~~~
../node_modules/simple-keyboard/build/index.d.ts:185:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'onKeyReleased' must be of type '(button: string) => any', but here has type '() => void'.

185     onKeyReleased?: () => void;
        ~~~~~~~~~~~~~
            ~~~~~~~~~~~~~
    'onKeyReleased' was also declared here..`

Version 2.26.1 is therefore not usable.

**Comment by hodgef** [comment]
Hello @thomas3577,

Sorry about that, I'll investigate.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @thomas3577 ,

I've released version `2.26.2` which should fix the issue. Feel free to update and give it a try,

Regards,
Francisco Hodge

**Comment by thomas3577** [comment]
Works fine with V2.26.2.
Thanks for the super fast fix :-)
